### ISSUE TITLE
Old Backup Files are not being removed.

### ISSUE THREAD

**Issue by RJ-Make** [Digressive/HyperV-Backup-Utility#10]
OS: Windows 10 Pro

Problem: Old Backup Files are not being removed. 
I do see "2021-10-16 01:09:00 [INFO] Removing compressed backups of NextCloud_G2 older than: 3 days" in the logs.

What debug info do you need?

**Comment by RJ-Make** [comment]
Sorry for the delay. 

Here is the requested info.

VM Name: 
NextCloud_G2

Batch-file Contents:
`
REM Hyper-V Virtual Machine Backup
set WorkingDir=G:\Hyper-V_BU_WrkDir
set BackUpTheseVMs=C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\hosts.txt
set BackupLocation=A:\ServerFolders\Acronis_Comp_BU\NextCloud_VM\BU\GEN_2
set BackupLogLocation=A:\ServerFolders\Acronis_Comp_BU\NextCloud_VM\BU\Logs
set PowerShellScriptLoc=C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1

PowerShell -ep bypass %PowerShellScriptLoc% -BackupTo %BackupLocation% -List %BackUpTheseVMs% -Wd %WorkingDir% -Keep 3 -Compress -L %BackupLogLocation%
`

**Comment by RJ-Make** [comment]
Thank You for all your hard work on this, I will update today and report back.

**Comment by RJ-Make** [comment]
Running into some problems using the lastest version. 

`At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:1217 char:28
+             $SmtpPort = "25"
+                            ~
The string is missing the terminator: ".
At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:449 char:21
+                     {
+                     ~
Missing closing '}' in statement block or type definition.
At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:447 char:17
+                 {
+                 ~
Missing closing '}' in statement block or type definition.
At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:442 char:13
+             {
+             ~
Missing closing '}' in statement block or type definition.
At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:416 char:14
+         else {
+              ~
Missing closing '}' in statement block or type definition.
At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:380 char:5
+     {
+     ~
Missing closing '}' in statement block or type definition.
At C:\FTPSyncFiles\Bat_Files\VM_BU_SCRIPTS\VMStartStop.ps1:265 char:1
+ {
+ ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString`

**Comment by RJ-Make** [comment]
<img width="469" alt="2021-10-31_11-40-04" src="https://user-images.githubusercontent.com/8496835/139591310-cf695b46-052c-476d-a65f-4dea7363fa53.png">

**Comment by Digressive** [comment]
Hi there, Sorry about that!

If you download the most recent version (I updated last night) it should work without those errors you posted.

**Comment by RJ-Make** [comment]
Perhaps I'm doing something wrong, as I'm getting the same errors. 

Here is the new scripts I copied just now. 
[VMStartStop.zip](https://github.com/Digressive/HyperV-Backup-Utility/files/7456354/VMStartStop.zip)


<img width="477" alt="2021-11-01_17-51-11" src="https://user-images.githubusercontent.com/8496835/139747055-73f4b06f-cfc8-4aed-8b29-4776948d666a.png">

**Comment by Digressive** [comment]
Just found the issue - there is a difference in the encoding of the script that you have. Did you copy & paste it from github into a txt file? If so, that's where the issue is coming from.

If you download as a zip from GutHub (under the Green "Code" button) then you'll get the script without the encoding issue.

**Comment by RJ-Make** [comment]
Sorry for the delay, 

That was it. Thank You!  I'll report back on the deletion issue now that you solved my stupidity.. :-)

**Comment by Digressive** [comment]
No problem at all!

I've been looking at the script today and believe I have fixed the issue you were having, so please check out the latest version: 21.11.05

**Comment by RJ-Make** [comment]
It appears your prev. version was indeed cleaning up the old back ups. I have downloaded (correctly this time :-) ) this new version and will test and report back.

**Comment by RJ-Make** [comment]
Latest version has solved the removal of old backup's. 

Thanks again for all your hard work.

**Comment by Digressive** [comment]
No problem, glad your problem is fixed! Thanks again
