### ISSUE TITLE
VM not being compressed and moved properly to the backup destination

### ISSUE THREAD

**Issue by SagarKandel** [Digressive/HyperV-Backup-Utility#11]
Hey Galvin,
Thank you for your script . We are trying to use it for our VM backups but for some reason, its only compressing the very first VM in the list and moves all other uncompressed VM's along with the first zipped VM to the destination folder.  
So, when the script tries to compress the next VM in the list, it errors out as there is nothing inside the working directory folder. 

Can you suggest the resolution?

Thank you again.

**Comment by Digressive** [comment]
I believe I have fixed this issue. Please let me know if you are still having problems.

**Comment by SagarKandel** [comment]
Hi Mike,
Thank you for your email. Yes it was fixed when i removed -Noperm switch.
Anyway thank you for your help. Your powershell script does help a lot.


~Sagar
