### ISSUE TITLE
Windows 10 Pro HyperV is not work -List

### ISSUE THREAD

**Issue by itkroplis** [Digressive/HyperV-Backup-Utility#12]
Hi! Is in understand correctly! -List not work on Windows 10 Pro Hyper-V?

**Comment by Digressive** [comment]
Hi there! 

-List should work on Win 10 Pro Hyper-V :)

**Comment by itkroplis** [comment]
Not work. I use as in vms-example.txt but I get error: 
"Cannot validate argument on parameter 'VmList'. The "Test-Path -Path $_ -PathType Leaf" validation script for the argument with value "D:\scripts\vms.txt" did not return
a result of True. Determine why the validation script failed, and then try the command again.
At line:1 char:69
+ ... kupTo M:\HyperV_VHD\Genera-Win10Pro1 -List D:\scripts\vms.txt -Wd D:\ ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Hyper-V-Backup.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Hyper-V-Backup.ps1"
    
.\Hyper-V-Backup.ps1 -BackupTo M:\HyperV_VHD\Genera-Win10Pro1 -List D:\scripts\vms.txt -Wd D:\temp -Keep 30 -Compress -Sz -SzOptions '-t7z' -L D:\scripts\logs

In D:\scripts\vms.txt :
GeneraWin10Pro1

get-vm

Name                       State   CPUUsage(%) MemoryAssigned(M) Uptime             Status             Version
----                       -----   ----------- ----------------- ------             ------             -------
GeneraWin10Pro1            Running 0           2048              2.21:29:39.3290000 Operating normally 9.0
KUBUNTU-DOCKER_10.11.10.11 Running 2           2048              08:56:18.0620000   Operating normally 9.0

**Comment by Digressive** [comment]
I'm not sure what could be going wrong. I use the -List feature daily and I'm not currently having this issue?

Here's a couple of tips that might help:

The vms.txt should contain the names of the VM's as they are named in Hyper-V, not the NetBIOS or DNS name.

Make sure you are running the latest version: 21.12.28!

**Comment by itkroplis** [comment]
I use latest version and VM names from PS get-vm
Where are the older versions available?

**Comment by itkroplis** [comment]
I understood where was problem. In stupidly Windows by default file extension is hidden. In PS I ls  to folder and I saw vms.txt.txt  Sorry for the inconvenience!
