### ISSUE TITLE
Error using -NoPerms

### ISSUE THREAD

**Issue by RJ-Make** [Digressive/HyperV-Backup-Utility#14]
Because it's taking 3+ hours to export and backup my VM, I thought I would try the -NoPerms method. 

I'm getting the error below. It almost seems like the script is not waiting until the Merge is complete when shutting down, but I'm not sure about that.  

Here is the bat command. (which works fine when not using -NoPerms)
`PowerShell.exe -ep bypass %PowerShellScriptLoc% -BackupTo %BackupLocation% -List %BackUpTheseVMs% -Wd %WorkingDir% -NoPerms -Keep 7 -Compress -Sz -SzOptions '-t7z' -L %BackupLogLocation%`

<img width="936" alt="2022-01-09_17-07-59" src="https://user-images.githubusercontent.com/8496835/148703205-c2b0150c-a0a6-4e65-8d78-066eb60527da.png">

**Comment by Digressive** [comment]
Just to update, working on this.

**Comment by itkroplis** [comment]
Your VM maybe be with snapshot?

**Comment by RJ-Make** [comment]
> Your VM maybe be with snapshot?

Yes, I do have snapshots turned on.

**Comment by Digressive** [comment]
Latest version 22.01.19 has a "wait for VM to be in certain state and status" check added.

**Comment by RJ-Make** [comment]
Fantastic, that is a work of beauty. Tested it just now and the added 'wait for state' worked perfectly. Took 3 min to complete the merge.

Thank You!
