### ISSUE TITLE
Windows Server 2016 Can BSOD if you don't disable VSS diag.

### ISSUE THREAD

**Issue by whtghst1** [Digressive/HyperV-Backup-Utility#17]
There is an known issue with Windows Server 2016 that has the legacy VSS diag enabled by default. This can cause the host to BSOD when doing exports. Although you do not want to leave it disabled after the VM exports are done. This is still needed for Windows Server Backup for the host to backup a baremetal recovery.

Consider adding this to the beginning of the export block before the check for WorkDir:
## Disable VSS Legacy Tracing on Windows Server 2016 or risk having BSOD on Hyper-V Host. Only needed during the export phase.
	If ($OSV -eq "10.0.14393") {
		Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\VSS\Diag -Name "(default)" -Value "Disabled"
	}

Then add this to end of the export block just above the comment "End of standard export block":
## Re-enable VSS Legacy Tracing on Windows Server 2016. This is needed for Windows Server Backup if running on Host server.
  If ($OSV -eq "10.0.14393") {
	  Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Services\VSS\Diag -Name "(default)" -Value "Enabled"
  }

**Comment by Digressive** [comment]
Thanks for this.

**Comment by Digressive** [comment]
Added fix to version 22.02.08
