### ISSUE TITLE
Log file name when using short date

### ISSUE THREAD

**Issue by Schui1024** [Digressive/HyperV-Backup-Utility#23]
Hi - Sorry to ask - 2 things if I may    (loving the script btw, has been so useful)

1 - When using -shortcode to use just the Year-month-date for the destination, the log file still retains the time in the file name.
    I'm looking to automate my own commands on the log file after completion, and whilst the date is simple to reference the time stamp is not so easy. Do you think it would be expected that the log file would also use the -shortdate effect? or perhaps add option for -Lshort for example.

2 - Is there any chance of adding a switch for including vm's that are off? ie -force or -incoff?
     Clients often have vm's that are powered down and only power up during automation sequencing, however I still want them backed up.

Many thanks in advance!

Schui

**Comment by Digressive** [comment]
-AllVms option added in Update 24.08.29
