### ISSUE TITLE
PS1 and  Windows11 unattended execute backup script problem.

### ISSUE THREAD

**Issue by itkroplis** [Digressive/HyperV-Backup-Utility#30]
Hi! I recently upgraded to Windows 11 and ran into a problem. This cannot happen completely automatically when executing a PS1 script. Manual approvals are required, which poisons the script's work. Any advice on how to deal with this? For now, the only thing (that I've found) that should work is signing the PS1 script. But it should be studied how it is done (I have not come across it).

**Comment by Digressive** [comment]
I run this script as it on Windows 11, Sever 2016, 2019 and 2022.

I'm not sure what the issue is that you're having but I don't think it is a problem unique to this script.
