### ISSUE TITLE
We really miss the option to check the created 7z archive!

### ISSUE THREAD

**Issue by glazkovalex** [Digressive/HyperV-Backup-Utility#33]
We really miss the option to check the created 7z archive!

**Comment by glazkovalex** [comment]
> I'm sorry I don't understand, what option?

Hello! 
I mean, the 7z archive may be created with an error due to a processor, memory, or disk failure. Therefore, many archivers, for example, Winzip and many backup creators, for example, Acronis, allow you to check the created archive and only after that consider the backup successfully created. 7z has the ability to check the archive, but only as a separate additional operation after creating the archive. `7z t archive.7z`
Thus, I suggest adding the "7zWithTest" parameter to your wonderful script, if available, after creating the archive, run a check of the created archive and only if successful consider the backup successfully created.

**Comment by glazkovalex** [comment]
I'm not good at scripts, but apparently before[ line 370](https://github.com/Digressive/HyperV-Backup-Utility/blob/465183ccfb6653a6d17e05c4a9c3085dc0fa8873/Hyper-V-Backup.ps1#L370) you need to insert a check for the presence of an additional parameter "7zWithTest" and, if available, run: 
```
& "$env:programfiles\7-Zip\7z.exe" t ("$CompressDir\$CompressFileNameSet")
```

**Comment by Digressive** [comment]
I understand, thank you for providing more information! I'm going to work on this for a future release.

**Comment by jlaraby** [comment]
The 7-zip test feature fails when the archive was created with a password. Here is what I added to the CompressFiles7zip function to allow the archive test to work:

`        $archivePassword = if ($SzSwitches -ne $null) {
                                $password = ($SzSwitches -split ',') | Where-Object { $_ -match '^-p(.*)' } | ForEach-Object { $matches[1] }
                                if ($password -ne "" -and $password -ne $null) {
                                    "-p$password"
                                } else { "" } 
                            } else { "" }

        $7zipTestOutput = & "$env:programfiles\7-Zip\7z.exe" $archivePassword -bso0 t $($GetTheFile.FullName) *>&1`

**Comment by Digressive** [comment]
@jlaraby Thank you for this!
