### ISSUE TITLE
Support Backup vm to Linux Samba?

### ISSUE THREAD

**Issue by dinghuaming** [Digressive/HyperV-Backup-Utility#35]
Hi, does it supporting  backup vm to linux samba?

**Comment by Digressive** [comment]
Hello! It does but only with the -NoPerms option. I've never got Hyper-V's export-VM functions to work with a non-Windows box.

**Comment by Digressive** [comment]
Update 24.08.29 has support for SMB with separate authentication which works with Linux samba.
