### ISSUE TITLE
Dot in VM's name

### ISSUE THREAD

**Issue by secretofthesteel** [Digressive/HyperV-Backup-Utility#8]
Hi,
Your script is great and I thank you for your work. 
There is small issuse. If I have a dot in VM's name it produces backup file without .7z extension but something like this: 
![sample](https://user-images.githubusercontent.com/16115539/123241678-a374c100-d4e1-11eb-92d5-4c2527e2073c.png)
My name is in form of domain syntax ("domain.eu").
Regards,
TG

**Comment by Digressive** [comment]
This issue should be "solved" in the most recent version (21.07.02)

The new version replaces any dots '.' with hyphens/dashes '-' in the file names.
