### ISSUE TITLE
Feature request: unsuccessful backup alert

### ISSUE THREAD

**Issue by secretofthesteel** [Digressive/HyperV-Backup-Utility#9]
Hi,
I would like to suggest one feature request for your great script. In case of failed backup it would send email with alert. What is important sctipt shouldn't delete old backups such case.

Best regards,
TG

**Comment by Digressive** [comment]
In the most recent update (21.12.28) i've added checks in place so that if a VM fails to backup, the old backup is not deleted and the error is logged.
